Use new BD injection method
* Clone from injector instead of stable16
* Don't require asar or extract the core
* Use the new (?) $SNAP env var to detect the snap location
* Fix persistent 'ERROR: Discord installation not found.'

diff --git a/betterdiscordctl b/betterdiscordctl
--- a/betterdiscordctl
+++ b/betterdiscordctl
@@ -17,10 +17,9 @@ flavors=('' canary ptb)
 discord=
 modules=
 bd_repo='https://github.com/rauenzi/BetterDiscordApp'
-bd_repo_branch=stable16
+bd_repo_branch=injector
 bd=
 copy_bd=
-env_asar=
 snap=
 flatpak=
 
@@ -29,7 +28,6 @@ flavor=
 core=
 xdg_config=${XDG_CONFIG_HOME:-$HOME/.config}
 data=${XDG_DATA_HOME:-$HOME/.local/share}/betterdiscordctl
-asar_bin=asar
 snap_bin=snap
 flatpak_bin=flatpak
 
@@ -54,8 +52,6 @@ Options:
                                  (default 'stable16')
   -b, --betterdiscord=DIRECTORY  Use specified BetterDiscord directory
   -c, --copy-bd                  Copy BD directory instead of symlinking
-      --env-asar[=COMMAND]       Use the asar in PATH (or the specified command)
-                                 instead of local
       --snap[=COMMAND]           Use the Snap version of Discord (optionally
                                  using the specified snap(1) command)
       --flatpak[=COMMAND]        Use the Flatpak version of Discord (optionally
@@ -74,7 +70,7 @@ EOF
 verbose() {
   if (( verbosity >= $1 )); then
     shift
-    printf '%s\n' "$1"
+    printf '%s\n' "$1" >&2
   fi
 }
 
@@ -183,16 +179,6 @@ while :; do
     -c|--copy-bd)
       copy_bd=yes
       ;;
-    --env-asar)
-      env_asar=yes
-      ;;
-    --env-asar=?*)
-      env_asar=yes
-      asar_bin=${1#*=}
-      ;;
-    --env-asar=)
-      die_non_empty '--env-asar'
-      ;;
     --snap)
       snap=yes
       copy_bd=yes
@@ -231,29 +217,21 @@ while :; do
 done
 
 mkdir -p "$data"
-[[ ! -f $data/bd_map ]] && touch "$data/bd_map"
+[[ -f $data/bd_map ]] || touch "$data/bd_map"
 
 bdc_find_modules() {
   declare -a all_modules
   all_modules=("$discord_config/"+([0-9]).+([0-9]).+([0-9])'/modules')
-  if ((! ${#all_modules[@]})); then
-    die 'ERROR: Discord modules directory not found.'
-  fi
+  ((${#all_modules[@]})) || die 'ERROR: Discord modules directory not found.'
   modules=${all_modules[-1]}
   verbose 1 "V: Found modules in $modules"
 }
 
 if [[ $snap ]]; then
-  desktop_file=/var/lib/snapd/desktop/applications/discord_discord.desktop
-  if [[ -f $desktop_file ]]; then
-    discord=$(sed -n 's/Icon=\(.*\)\/discord.png/\1/p' $desktop_file)
-  else
-    if [[ -d /snap/discord ]]; then
-      discord=$(readlink -f /snap/discord/current/usr/share/discord)
-    else
-      discord=$(readlink -f /var/lib/snapd/snap/discord/current/usr/share/discord)
-    fi
-  fi
+  # shellcheck disable=SC2016
+  # Expansion should happen inside snap's shell.
+  snap_location=$("$snap_bin" run --shell discord <<< 'echo "$SNAP" 1>&3' 3>&1)
+  discord=${snap_location:?}/usr/share/discord
   verbose 2 "VV: Checking $discord"
   if [[ -d $discord ]]; then
     verbose 1 "V: Using Discord at $discord"
@@ -269,15 +247,15 @@ fi
 
 if [[ $flatpak ]]; then
   # flatpak sucks and doesn't use stderr for warnings.
-  # https://github.com/flatpak/flatpak/blob/13e449b5033d063f0df8b2d496c6ff929543239c/app/flatpak-main.c#L259-L286
-  # This really should be better about directories with newlines, but...
-  # Translations. So we're just going to grab the last line and hope for the best.
+  # https://github.com/flatpak/flatpak/blob/13e449b/app/flatpak-main.c#L259-L286
+  # This really should be better for directories with newlines, but...
+  # We're just going to grab the last line and hope for the best.
   flatpak_location=$("$flatpak_bin" info --show-location com.discordapp.Discord)
   flatpak_location=${flatpak_location##*$'\n'}
-  discord=$flatpak_location/files/extra
-  verbose 2 "VV: Checking $discord" >&2
+  discord=${flatpak_location:?}/files/extra
+  verbose 2 "VV: Checking $discord"
   if [[ -d $discord ]]; then
-    verbose 1 "V: Using Discord at $discord" >&2
+    verbose 1 "V: Using Discord at $discord"
     # We can avoid the earlier warning problem by using FD 3. yay.
     # shellcheck disable=SC2016
     # Expansion should happen inside flatpak's shell.
@@ -297,62 +275,51 @@ if [[ $cmd != upgrade ]]; then
     for scandir in "${scan[@]}"; do
       verbose 2 "VV: Scanning $scandir"
       for flavor in "${flavors[@]}"; do
-        verbose 2 "VV: Trying flavor '$flavor'" >&2
+        verbose 2 "VV: Trying flavor '$flavor'"
         shopt -s nocaseglob
         for discord in "$scan"/discord?(-)"$flavor"; do
           shopt -u nocaseglob
           if [[ -d $discord ]]; then
-            verbose 1 "V: Using Discord at $discord" >&2
+            verbose 1 "V: Using Discord at $discord"
             discord_config=$xdg_config/discord${flavor,,}
             if [[ ! -d $discord_config ]]; then
-              printf 'WARN: Config directory not found for Discord %s (%s, %s).\n' "$flavor" "$discord" "$discord_config" >&2
+              printf 'WARN: Config directory not found for Discord %s (%s, %s).\n' \
+                "$flavor" "$discord" "$discord_config" >&2
               continue 2
             fi
             if [[ -z $modules ]]; then
               bdc_find_modules
             else
               # --modules
-              if [[ ! -d $modules ]]; then
-                die 'ERROR: Discord modules directory not found.'
-              fi
+              [[ -d $modules ]] || die 'ERROR: Discord modules directory not found.'
             fi
             break 3
           fi
         done
       done
     done
-    die 'ERROR: Discord installation not found.'
   else
     flavor=$flavors
     # --discord and --modules
-    if [[ -z $modules ]]; then
-      die_with_help 'ERROR: "--discord" requires "--modules" to also be set.'
-    fi
-    if [[ ! -d $discord ]]; then
-      die 'ERROR: Discord installation not found.'
-    fi
-    if [[ ! -d $modules ]]; then
-      die 'ERROR: Discord modules directory not found.'
-    fi
+    [[ -z $modules ]] && die_with_help 'ERROR: "--discord" requires "--modules" to also be set.'
+    [[ -d $discord ]] || die 'ERROR: Discord installation not found.'
+    [[ -d $modules ]] || die 'ERROR: Discord modules directory not found.'
   fi
+  [[ -d $discord ]] || die 'ERROR: Discord installation not found.'
   core=$modules/discord_desktop_core
-  if [[ ! -d $core ]]; then
-    die "ERROR: Directory 'discord_desktop_core' not found in $(readlink -f "$modules")"
-  fi
+  [[ -d $core ]] || die "ERROR: Directory 'discord_desktop_core' not found in $(readlink -f "$modules")"
 fi
 
 # Commands
 
 bdc_status() {
-  core_patched=no
   index_mod=no
   linked_dir=no
   linked_repo=no
-  if [[ -d $core/core ]]; then
-    core_patched=yes
-    if [[ -h $core/core/node_modules/betterdiscord ]]; then
-      linked_dir=$(readlink "$core/core/node_modules/betterdiscord")
-      if pushd "$core/core/node_modules/betterdiscord" >/dev/null; then
+  if [[ -d $core/injector ]]; then
+    if [[ -h $core/injector ]]; then
+      linked_dir=$(readlink "$core/injector")
+      if pushd "$core/injector" >/dev/null; then
         linked_repo=$(git remote get-url origin 2>/dev/null || printf 'no\n')
         popd >/dev/null
       else
@@ -363,59 +330,54 @@ bdc_status() {
   if [[ ! -f $core/index.js ]]; then
     index_mod='(missing) no'
   else
-    if ! grep -q 'asar' "$core/index.js"; then
-      index_mod=yes
-    fi
+    grep -q 'injector' "$core/index.js" && index_mod=yes
   fi
 
   printf 'Discord: %s
 Modules: %s
-Core patched: %s
 Index modified: %s
-Linked core directory: %s
-Linked core repository: %s\n' \
-    "$discord" "$modules" "$core_patched" "$index_mod" "$linked_dir" "$linked_repo"
+Linked injector directory: %s
+Linked injector repository: %s\n' \
+    "$discord" "$modules" "$index_mod" "$linked_dir" "$linked_repo"
 }
 
 bdc_install() {
+  [[ -d $core/injector ]] && die 'ERROR: Already installed.'
+
+  # Clean up legacy cruft
   if [[ -d $core/core ]]; then
-    die 'ERROR: Already installed.'
+    printf 'Removing legacy core directory...\n' >&2
+    rm -rf "$core/core"
   fi
 
   bd_patch
-  bd_loader
+  bd_injector
 
   printf 'Installed. (Restart Discord if necessary.)\n' >&2
 }
 
 bdc_reinstall() {
-  if [[ ! -d $core/core ]]; then
-    printf 'Not installed.\n' >&2
-    exit 1
-  fi
+  [[ -d $core/injector ]] || die 'Not installed.'
 
   bdc_kill
 
-  verbose 1 'V: Removing old core folder.' >&2
-  rm -rf "$core/core"
+  verbose 1 'V: Removing old injector folder.'
+  rm -rf "$core/injector"
 
   bd_patch
-  bd_loader
+  bd_injector
 
   printf 'Reinstalled.\n' >&2
 }
 
 bdc_update() {
-  if [[ ! -d $core/core ]]; then
-    printf 'Not installed.\n' >&2
-    exit 1
-  fi
+  [[ -d $core/injector ]] || die 'Not installed.'
 
-  if ! pushd "$core/core/node_modules/betterdiscord" >/dev/null; then
-    if [[ -h $core/core/node_modules/betterdiscord ]]; then
-      die 'ERROR: Core BetterDiscord symbolic link is broken.'
+  if ! pushd "$core/injector" >/dev/null; then
+    if [[ -h $core/injector ]]; then
+      die 'ERROR: BetterDiscord injector symbolic link is broken.'
     else
-      die 'ERROR: Core BetterDiscord location is not a directory.'
+      die 'ERROR: BetterDiscord injector location is not a directory.'
     fi
   fi
   if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
@@ -429,10 +391,7 @@ bdc_update() {
 }
 
 bdc_uninstall() {
-  if [[ ! -d $core/core ]]; then
-    printf 'Not installed.\n' >&2
-    exit 1
-  fi
+  [[ -d $core/injector ]] || die 'Not installed.'
 
   bdc_kill
   bd_unpatch
@@ -443,12 +402,6 @@ bdc_uninstall() {
   if [[ -z $(bd_map_get_n "$bd_n") ]]; then
     verbose 2 "VV: Removing $data/bd/$bd_n"
     rm -rf "$data/bd/$bd_n"
-  fi
-
-  # Clean up legacy cruft
-  if [[ -d $discord/resources/app ]]; then
-    printf 'Removing legacy app directory...\n' >&2
-    rm -r "$discord/resources/app"
   fi
 
   printf 'Uninstalled.\n' >&2
@@ -464,9 +417,9 @@ bdc_upgrade() {
   if [[ ${PIPESTATUS[0]} -ne 0 ]]; then
     die "ERROR: GitHub couldn't be reached to check the version."
   fi
-  verbose 2 "VV: Script location: $SOURCE" >&2
-  verbose 1 "V: Local version: $VERSION" >&2
-  verbose 1 "V: GitHub version: $github_version" >&2
+  verbose 2 "VV: Script location: $SOURCE"
+  verbose 1 "V: Local version: $VERSION"
+  verbose 1 "V: GitHub version: $github_version"
   semver_diff=$(Semver::compare "$github_version" "$VERSION")
   if [[ $semver_diff -eq 1 ]]; then
     printf 'Downloading betterdiscordctl...\n' >&2
@@ -487,35 +440,14 @@ bdc_upgrade() {
 
 # Implementation functions
 
-bdc_asar() {
-  if [[ $env_asar ]]; then
-    "$asar_bin" "$@"
-  else
-    mkdir -p "$data/asar" || die "Couldn't create $data/asar."
-    pushd "$data/asar" >/dev/null
-    if [[ ! -d $data/asar/node_modules ]]; then
-      printf '{"devDependencies":{"asar":"*"}}\n' > package.json
-      printf 'Installing asar...\n' >&2
-      npm install || die "Couldn't install $data/asar."
-    else
-      printf 'Updating asar...\n' >&2
-      npm update || die "Couldn't update $data/asar."
-    fi
-    popd >/dev/null
-    "$data/asar/node_modules/asar/bin/asar.js" "$@"
-  fi
-}
-
 bdc_kill() {
   declare process_name=Discord
-  if [[ $flavor ]]; then
-    process_name+=" $flavor"
-  fi
+  [[ $flavor ]] && process_name+=" $flavor"
   printf 'Killing %s processes...\n' "$process_name" >&2
   pkill -exi -KILL "discord-?$flavor" || printf 'No active processes found.\n' >&2
 }
 
-bd_loader() {
+bd_injector() {
   if [[ -z $bd ]]; then
     bd=$data/bd/$(bd_map_add "$discord" "$bd_repo")
     if [[ ! -d $bd ]]; then
@@ -525,35 +457,29 @@ bd_loader() {
   fi
 
   if [[ $copy_bd ]]; then
-    verbose 1 'V: Copying core loader...' >&2
-    cp -r "$bd" "$core/core/node_modules/betterdiscord"
+    verbose 1 'V: Copying BetterDiscord injector...'
+    cp -r "$bd" "$core/injector"
   else
-    verbose 1 'V: Linking core loader...' >&2
-    ln -s "$bd" "$core/core/node_modules/betterdiscord"
+    verbose 1 'V: Linking BetterDiscord injector...'
+    ln -s "$bd" "$core/injector"
   fi
 }
 
 bd_patch() {
-  verbose 1 'V: Unpacking core asar...' >&2
-  bdc_asar e "$core/core.asar" "$core/core"
-
-  if [[ ! -d $core/core ]]; then
-    die 'ERROR: Failed to unpack core asar.' \
-        'You may want to install or update nodejs and npm.'
+  if ! grep -q 'injector' "$core/index.js"; then
+    verbose 1 'V: Injecting into index.js...'
+    sed -i "$core/index.js" \
+      -e "1i require('./injector');" \
+      -e "s/core'/core.asar'/"
   fi
-
-  verbose 1 'V: Patching core entry...' >&2
-  sed -i "$core/index.js" -e "s/core\\.asar'/core'/g"
-  sed -i "$core/core/app/mainScreen.js" \
-      -e "/use strict/a var _betterDiscord = require('betterdiscord');\\nvar _betterDiscord2;" \
-      -e "/mainWindow = new/a \\  _betterDiscord2 = new _betterDiscord.BetterDiscord(mainWindow);" \
-      -e "/nodeIntegration: false/d" -e "/webPreferences:/a \\      nodeIntegration: true,"
 }
 
 bd_unpatch() {
-  verbose 1 'V: Removing core folder from modules...' >&2
-  sed "s/core'/core.asar'/g" -i "$core/index.js"
-  rm -rf "$core/core"
+  verbose 1 'V: Removing BetterDiscord injection...'
+  sed -i "$core/index.js" \
+    -e '/injector/d' \
+    -e "s/core'/core.asar'/"
+  rm -rf "$core/injector"
 }
 
 bd_map_entry_n() {
@@ -561,8 +487,9 @@ bd_map_entry_n() {
 }
 
 bd_map_fresh() {
-  verbose 2 'VV: Generating fresh bd_map number...' >&2
-  bd_map_entry_n "$data/bd_map" | sort | awk 'BEGIN {max=-1} NF != 0 {if ($1>max+1) {exit}; max=$1} END {print max+1}'
+  verbose 2 'VV: Generating fresh bd_map number...'
+  bd_map_entry_n "$data/bd_map" | sort | awk \
+    'BEGIN {max=-1} NF != 0 {if ($1>max+1) {exit}; max=$1} END {print max+1}'
 }
 
 bd_map_add() {
